### ISSUE TITLE
"About Us" page refers to BSD license rather than Creative Commons

### ISSUE THREAD

**Issue by timw6n** [holoviz/colorcet#100]
As above, the [about us page](https://colorcet.holoviz.org/about.html) (source https://github.com/holoviz/colorcet/blob/master/doc/about.rst) looks to be referencing the wrong license. 

Should probably be changed to say CC-BY there, to match the LICENSE.txt file in the repository.

Suspect the text referencing BSD has crept in as boilerplate from other Holoviz projects.

**Comment by jbednar** [comment]
Good catch! Interested in making a PR to fix that?

**Comment by timw6n** [comment]
Done. Not really used .rst files before so hope I've got the syntax correct. https://github.com/holoviz/colorcet/pull/101
