### ISSUE TITLE
License in repository is CC-BY, but website says BSD

### ISSUE THREAD

**Issue by lcniel** [holoviz/colorcet#109]
I was doing due diligence for the packages I'm planning to install by default in my software, and I noticed that the `LICENSE.txt` file and `about.rst` state that `colorcet` is licensed under `CC-BY 3.0` whereas [the About page of colorcet.holoviz.org](https://colorcet.holoviz.org/about.html) states BSD. It would be good if this divergence was resolved, perhaps a documentation build job just needs to be run or similar? I'm mainly a GitLab user, so I'm not entirely sure.

**Comment by jbednar** [comment]
Good point! Happy to accept a PR to fix the About page.

**Comment by lcniel** [comment]
> Good point! Happy to accept a PR to fix the About page.

It's not actually clear to me what the exact issue is but the `about.rst` is aligned with the repo. It looks however that it's not being deployed (`deploy_dev` and `deploy_main` are not being triggered when I look at recent jobs). Perhaps there is some issue with the `docs.yaml`? Not familiar enough with the inner workings github workflows or the project to fix quickly myself, unfortunately.

**Comment by jbednar** [comment]
Oops; should have read your message more closely. The website build is only published for releases, not for scheduled testing jobs, and there hasn't been a release since that was fixed in the source. @maximlt , I don't see an explicit workflow action in colorcet to trigger to force a build out of band; can you add one as we have for other projects?

**Comment by jbednar** [comment]
Ah, I was looking for it in All Workflows:

<img width="937" alt="image" src="https://user-images.githubusercontent.com/1695496/236699486-07f30067-cb88-45ae-9495-2da4583ecc5a.png">

Sorry for the noise. I've built the site to main; hope it works!

**Comment by lcniel** [comment]
Looks good to me, thanks for the quick action!

**Comment by jbednar** [comment]
No problem, and thanks for letting us know!
