### ISSUE TITLE
remove pyct / param dependency

### ISSUE THREAD

**Issue by Jhsmit** [holoviz/colorcet#118]
in #84 explicit `param` dependency was removed, but since `pyct` is still a dependency, which requires `param`,  there is still a param reliance. 

it seems that pyct is only being used for command-line use, so maybe it can be moved to optional dependencies

**Comment by philippjfr** [comment]
Strong +1, we'll be working on migrating away from param.version and pyct for all of our projects but can't promise a timeline.

**Comment by maximlt** [comment]
Done in https://github.com/holoviz/colorcet/pull/120
