### ISSUE TITLE
[DOCS] Explain matplotlib get_cmap function

### ISSUE THREAD

**Issue by banesullivan** [holoviz/colorcet#32]
Would it make sense to implement a `get_cmap` function as `colorcet.cm.get_cmap` that could override Matplotlib's so that external libraries using MPL's `get_cmap` could just replace it with Colorcet's `get_cmap` if Colorcet is available at runtime? This would make interfaceing with Colorcet super easy for other libraries already leveraging MPL's colormaps.

I'm thinking that this function would have the same arguments and behavior as MPL's `get_cmap` but it would also grab Colorcet colormaps by name and default to Colorcet if MPL has a similarly named colormap.

**Comment by jbednar** [comment]
Colorcet's colormaps are already available from Matplotlib's get_cmap, but prefixed with "cet_":

```
from matplotlib.cm import get_cmap
import colorcet

get_cmap("cet_fire")
```

```
<matplotlib.colors.LinearSegmentedColormap at 0x11d7c2c50>
```

**Comment by banesullivan** [comment]
Interesting... I did not realize that was possible. Did I miss this in the docs?

**Comment by jbednar** [comment]
Third paragraph of http://colorcet.pyviz.org/user_guide/index mentions:

> The same colormaps are also registered with matplotlib's string-based dictionary with the prefix cet_, making them available by name within various matplotlib functions (e.g. cet_linear_kryw_0_100_c71, cet_linear_kryw_0_100_c71_r, cet_fire, or cet_fire_r). 

But it doesn't specifically mention `get_cmap`, so we'd happily accept a PR to explain it better.  Basically, if you can think of how to make sure no one else misses it, please do! :-)  

If you have enough time to make matplotlib and bokeh examples for the user guide, illustrating the various ways to use them, we'd love to have those too!
