### ISSUE TITLE
Ensure that categorical colormaps are registered as ListedColormap

### ISSUE THREAD

**Issue by philippjfr** [holoviz/colorcet#39]
Generally categorical colormaps should be registered as `ListedColormap` instead of a `LinearSegmentedColormap` so the Glasbey colormaps should be switched.

**Comment by kcpevey** [comment]
`__init__.mpl_cm` is always using `LinearSegmentedColormap` but it needs to have some added logic to use `ListedColormap` for categorical colormaps. Perhaps through some mapping on the groups/name parameter.
