### ISSUE TITLE
pyct dependency used inside setup.py

### ISSUE THREAD

**Issue by jsharpe** [holoviz/colorcet#41]
The pyct.build package is imported and used before setup is called and so a build from a fresh python environment fails because it can't import pyct.build as it hasn't yet been installed as a build dependency.

**Comment by ceball** [comment]
Please could you give more information about what commands/tools you are
using, and what you are trying to do?

pyct is listed as a build dependency in pyproject.toml.

**Comment by ceball** [comment]
I'm going to close this as I can't see an action for us, but please re-open if you can say what we should be doing instead. Thanks

**Comment by jsharpe** [comment]
Sorry for the delay in responding - the issue appears if you do pip download without first install pyct. It appears that pip download runs setup.py without installing build dependencies.

**Comment by jbednar** [comment]
Sounds like it may be a very old version of pip?

**Comment by jsharpe** [comment]
Its version 19.0.3

**Comment by jsharpe** [comment]
With commandline arguments pip3 download --no-binary :all: --no-deps --dest ${DOWNLOAD_LOCATION} -r requirements.txt

**Comment by jbednar** [comment]
Isn't that the behavior you'd expect with `--no-deps`?

**Comment by jsharpe** [comment]
No, because the requirements.txt file includes the pyct dep as generated from pip-tools. I have to download with --no-deps because I haven't yet built all the binary dependencies needed to install the packages at the point at which I am calling pip download. If I have to work around by installing pyct before download then that's fine but if I can avoid that it'd be great.

**Comment by ceball** [comment]
Could you somehow demonstrate how this problem is specific to colorcet and does not happen for another package with build-time dependencies [PEP-0518](https://www.python.org/dev/peps/pep-0518/)? That would help us figure out if we have not set things up correctly, or if our setup has become out of date (both possible). Some possible projects to try off the top of my head: numpy, pytest (but there'll be others). Alternatively, do you have a different suggestion for handling build-time dependencies?




Thanks!

**Comment by jsharpe** [comment]
For reference the issue is todo with https://github.com/pypa/pip/issues/6222 - the use of no-binary effectively bypasses the PEP-517 build process which includes pulling in the dependencies as defined in pyproject.toml and hence why I was seeing the missing dependency. Upgrading to pip 19.3.1 fixes this as it includes the fix https://github.com/pypa/pip/issues/6993

In short this was a pip issue with the --no-binary flag.

**Comment by ceball** [comment]
Thanks for the update!
