### ISSUE TITLE
Colorblind-safe categorical map?

### ISSUE THREAD

**Issue by wmayner** [holoviz/colorcet#52]
#### Describe the solution you'd like
It would be nice to have a categorical colormap similar to the `glasbey` maps, but that is colorblind-safe.

#### Additional context
The pair `cc.b_glasbey_category10[2]` (`#2ba02b`) and `cc.b_glasbey_category10[3]` (`#d62628`) are not colorblind-safe.

**Comment by jbednar** [comment]
The way the categorical colors are generated is to create a gamut of possible colors, then iteratively choose colors within that gamut that are most dissimilar from all the preceding colors.  You could use a color-blind-safe definition of color similarity when doing so, but that would require modifying the underlying code. I think it's probably easier to simply prune out non red-green colorblind-safe colors by eliminating either the green or the red portion of the gamut.  In fact, the `cool` and `warm` Glasbey variants already do this:

![image](https://user-images.githubusercontent.com/1695496/81588095-9f3d2100-937d-11ea-8ae3-af4aae3c0cb8.png)

These color sets were not intentionally constructed to be colorblind safe, and you can probably do a better job if you have a good model to guide which colors to select, pruning specifically the ones likely to be confused by a dichromat.  We'd be happy to accept a contribution of improved `cool` or `warm` color sets that are specifically validated for their colorblind safety properties, using either method (dichromat-safe color similarity metric, or color space pruning).

In any case, note that the specific set you mention (`glasbey_category10`) is constructed by taking the first 10 colors as fixed (from the externally defined [D3 `category10`](https://nanx.me/ggsci/reference/pal_d3.html) colormap). Those 10 colors include red and green, so any color set starting with those colors will never be colorblind safe.  So it is not possible to create anything like `glasbey_category10`, intended as a drop-in replacement for and extension of `category10`; it would need to be something like our `cool` or `warm` palettes that avoid the confusing red/green combination.

**Comment by jbednar** [comment]
Closing since there's a solution for now, but we'd still be happy to accept a specifically constructed colorblind-safe categorical map.
