### ISSUE TITLE
Possibility of change in License info on pypi from "Other/Proprietary License (CC-BY License)" to more explicit Creative Commons Intl ?

### ISSUE THREAD

**Issue by pnsvk** [holoviz/colorcet#57]
This is blocking us from installing multiple other packages which have colorcet as dependency.. eg: Holoviews, Datashader, etc.

**Comment by pnsvk** [comment]
Would be of great help, as this is blocking our installations in our Org.

**Comment by jbednar** [comment]
As listed in https://github.com/holoviz/colorcet/blob/master/LICENSE.txt, this project is governed by the "Creative Commons Attribution 4.0 International Public License (CC-BY)". The setup.py file contains:

```
    license='CC-BY License',
    classifiers=[
        "License :: Other/Proprietary License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Development Status :: 5 - Production/Stable",
    ],
```

And https://pypi.org/project/colorcet/ lists the license as "License: Other/Proprietary License (CC-BY License)".   I assume you're asking for "Other/Proprietary License" to be replaced with something like "License :: Creative Commons Attribution 4.0 International Public License" and to have a new release? We can do that, but I would think the `license` field is explicit enough already.

**Comment by pnsvk** [comment]
Thank you for your response.. Yeah.. Our internal org tooling was discarding the package procurement with the phrases "Other / Proprietary" part of it.. 
Can you please let me know if it can be made more explicit that it indeed is CC alone, in its intent..

**Comment by jbednar** [comment]
Fixed, but won't update on PyPi until the next release. Shouldn't be too long until a new release, as there are new colormaps available upstream and we'll want to get those in.

**Comment by jbednar** [comment]
Release 2.0.3 is building at https://travis-ci.org/github/holoviz/colorcet/jobs/755017496, and if it succeeds I think the metadata should update at PyPi.

**Comment by pnsvk** [comment]
While your [commit](https://github.com/holoviz/colorcet/commit/e913faf1c1728c43efee62a6ee0873ee17ee0cff) looks clean, can you please kindly help check where the Meta information is getting populated from on PyPI ?

![561956CC-9A49-41BF-8493-403C1B3FD720_4_5005_c](https://user-images.githubusercontent.com/30823233/104988719-cedd1680-5a3e-11eb-9f2c-4674e271e791.jpeg)

**Comment by jbednar** [comment]
Turns out that PyPi only accepts a [limited set of classifiers](https://pypi.org/classifiers/), so I had to update it separately to use `License : OSI Approved` in the classifiers, with the actual license specified in `license`.

**Comment by pnsvk** [comment]
Thank you for all the responses and the merge.. Will work on it with my internal (Org.) contacts to see if they could do something about it.
Thank you once again.

**Comment by jbednar** [comment]
Do something about what? Is "License: OSI Approved" not already ok?
