### ISSUE TITLE
color palette name is not recognized

### ISSUE THREAD

**Issue by ivan-marroquin** [holoviz/colorcet#67]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
python 3.6.5
matplotlib 3.2.2
colorcet 2.0.6
#### Description of expected behavior and the observed behavior

I want to generate a 3d scatter plot using a rainbow color palette from colorcet package

#### Complete, minimal, self-contained example code that reproduces the issue
< code to generate a 3d data set>

fig= plt.figure(figsize= (10,10))
    
ax= plt.axes(projection= '3d')
    
ax.grid(b = True, color ='grey', linestyle ='-.', linewidth = 0.3, alpha = 0.2)
    
map1= ax.scatter(clusterable_embedding[:,0], clusterable_embedding[:,1], clusterable_embedding[:,2], 
                             c= num_points, cmap= cc.cm.rainbow_bgyr_35_85_c72, alpha= 0.7)
    
ax.set_title('n_neighbors 10 min_dist 0.1 spread 1.0 learning rate 1.0')
    
ax.set_xlabel('X-axis', fontweight ='bold')

ax.set_ylabel('Y-axis', fontweight ='bold')
    
ax.set_zlabel('Z-axis', fontweight ='bold')
    
fig.colorbar(map1, ax= ax, shrink= 0.5, aspect= 5)
        
plt.show()
```
# code goes here between backticks

```

#### Stack traceback and/or browser JavaScript console output
Traceback (most recent call last):
  File "test_umap_hdbscan.py", line 130, in <module>
    c= num_points, cmap= cc.rainbow_bgyr_35_85_c72, alpha= 0.7)
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 2239, in scatter
    patches = super().scatter(xs, ys, s=s, c=c, *args, **kwargs)
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\matplotlib\__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\matplotlib\cbook\deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\matplotlib\axes\_axes.py", line 4447, in scatter
    collection.set_cmap(cmap)
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\matplotlib\cm.py", line 313, in set_cmap
    cmap = get_cmap(cmap)
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\matplotlib\cm.py", line 134, in get_cmap
    cbook._check_in_list(sorted(cmap_d), name=name)
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\matplotlib\cbook\__init__.py", line 2145, in _check_in_list
    .format(v, k, ', '.join(map(repr, values))))
ValueError: [[0, 0.20387, 0.96251], [0, 0.21524, 0.9514], [0, 0.22613, 0.94031], [0, 0.23654, 0.92923], [0, 0.24654, 0.91817], [0, 0.2562, 0.90712], [0, 0.26557, 0.89608], [0, 0.27465, 0.88506], [0, 0.28348, 0.87405], [0, 0.29209, 0.86305], [0, 0.30047, 0.85206], [0, 0.3087, 0.84109], [0, 0.31672, 0.83013], [0, 0.32458, 0.81917], [0, 0.33232, 0.80823], [0, 0.3399, 0.7973]
.....
is not a valid value for name; supported values are 'Accent', 'Accent_r', 'Blues', 'Blues_r', 'BrBG', 'BrBG_r', 'BuGn', 'BuGn_r', 'BuPu', 'BuPu_r', 'CMRmap', 'CMRmap_r', 
....
#### Screenshots or screencasts of the bug in action
Note that I also tried this command:
map1= ax.scatter(clusterable_embedding[:,0], clusterable_embedding[:,1], clusterable_embedding[:,2], 
                             c= num_points, cmap= cc.rainbow_bgyr_35_85_c72, alpha= 0.7)

and I still got the same problem

Many thanks,

Ivan

**Comment by jbednar** [comment]
Here the error messages suggest that you are passing a Bokeh palette, which is a list of color values, to Matplotlib, which expects a matplotlib colormap object. See the colorcet docs for how to access colorcet maps as Matplotlib colormaps so that you can use them in this case.

**Comment by jbednar** [comment]
From that error message you were definitely not passing a matplotlib colormap. Here's what you should see:

```
from matplotlib import pyplot as plt
import numpy as np, colorcet as cc
fig= plt.figure(figsize= (10,10))
ax= plt.axes(projection= '3d')
ax.grid(b = True, color ='grey', linestyle ='-.', linewidth = 0.3, alpha = 0.2)
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], np.int32)
map1= ax.scatter(data[:,0], data[:,1], data[:,2],
                 c= [2,4,6], cmap= cc.cm.rainbow_bgyr_35_85_c72, alpha= 0.7)
```
![image](https://user-images.githubusercontent.com/1695496/117983444-936f9c00-b2fc-11eb-9920-5c24ee5d44eb.png)
